package powers;

public enum PowerStat {
    FLAT_HP,
    HP_PERCENT,
    FLAT_ATK,
    ATK_PERCENT,
    FLAT_DEF,
    DEF_PERCENT,
    FLAT_SPEED,
    SPEED_PERCENT,
    SAME_ELEMENT_DAMAGE_BONUS,
    EFFECT_HIT,
    EFFECT_RES,
    BREAK_EFFECT,
    HEALING,
    DAMAGE_BONUS,
    DAMAGE_TAKEN,
    DEFENSE_REDUCTION,
    DEFENSE_IGNORE,
    RES_PEN,
    CRIT_CHANCE,
    CRIT_DAMAGE,
    ENERGY_REGEN,
    TAUNT_VALUE,
    WEAKNESS_BREAK_EFF
}
